
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module hm1(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,

	//////////// SW //////////
	SW 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// LED //////////
output		     [7:0]		LED;

//////////// KEY //////////
input 		     [1:0]		KEY;

//////////// SW //////////
input 		     [3:0]		SW;


//=======================================================
//  REG/WIRE declarations
//=======================================================



//=======================================================
//  Structural coding
//=======================================================
	souf1 u0 (
		.clk_clk                             (CLOCK_50),                             //                          clk.clk
		.reset_reset_n                       (KEY[0]),                       //                        reset.reset_n
		.switches_external_connection_export (SW), // switches_external_connection.export
		.button_external_connection_export   (KEY[1]),   //   button_external_connection.export
		.my_custom_ip_0_conduit_end_export   (LED)    //   my_custom_ip_0_conduit_end.export
	);




endmodule
